name: Releases

on: 
  push:
    tags:
      - '*' # Triggers on any tag push (e.g., v1.0, v2.3.4)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Zip the modpack folder into pack.zip
      - name: Zip modpack folder
        run: |
          cd modpack
          zip -r ../pack.zip .

      # Create a GitHub Release and attach the modpack ZIP
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "pack.zip"
          body: "Automated release for modpack version ${{ github.ref_name }}"
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
